# Generated by Django 4.2.7 on 2023-12-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasem', models.DateField(verbose_name='Día de la semana')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obrasoc', models.CharField(max_length=100, verbose_name='Obra Social')),
                ('tarifa', models.FloatField(verbose_name='Precio de consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(verbose_name='Documento de Identidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('sexo', models.CharField(max_length=20, verbose_name='Sexo')),
                ('nacimiento', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('mail_paciente', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefono_paciente', models.IntegerField(verbose_name='Teléfono')),
                ('provincia', models.CharField(max_length=100)),
                ('partido', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(verbose_name='Nro. de matrícula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('mail_prof', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefono_prof', models.IntegerField(verbose_name='Teléfono')),
                ('costo_consulta', models.FloatField(verbose_name='Precio de consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasem', models.DateField(verbose_name='Día de la semana')),
                ('hora_desde', models.DateTimeField(verbose_name='Horario del turno')),
                ('duracion', models.IntegerField(verbose_name='Duración del turno')),
            ],
        ),
    ]
