# Generated by Django 4.2.7 on 2023-12-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosmedicos', '0002_paciente_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='matricula',
            field=models.IntegerField(default=0, verbose_name='Nro. de matrícula'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='especialidad_listado',
            field=models.IntegerField(default=0, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='turno',
            name='dni',
            field=models.IntegerField(default=0, verbose_name='Documento de Identidad'),
        ),
        migrations.AddField(
            model_name='turno',
            name='matricula',
            field=models.IntegerField(default=0, verbose_name='Nro. de matrícula'),
        ),
    ]
