# Generated by Django 5.0 on 2023-12-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosmedicos', '0004_alter_turno_hora_desde'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='id_espe',
            field=models.IntegerField(null=True, verbose_name='código especialidad'),
        ),
        migrations.AddField(
            model_name='horario',
            name='duracion',
            field=models.IntegerField(default=20, verbose_name='duración de consulta'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_desde',
            field=models.TimeField(default='12:00', verbose_name='hora de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_hasta',
            field=models.DateTimeField(default='15:00', verbose_name='hora de fin de consulta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='id_obrasoc',
            field=models.IntegerField(default='1', verbose_name='codigo obra social'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social_listado',
            field=models.IntegerField(default='1', verbose_name='obra/s social/es'),
            preserve_default=False,
        ),
    ]
