# Generated by Django 5.0 on 2023-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosmedicos', '0005_especialidad_id_espe_horario_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_desde',
            field=models.TimeField(default='2023-12-11 12:00'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_hasta',
            field=models.DateTimeField(default='2023-12-11 12:00', verbose_name='hora de fin de consulta'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_desde',
            field=models.TimeField(default='2023-12-11 12:00', verbose_name='Horario del turno'),
        ),
    ]
