# Generated by Django 5.0 on 2023-12-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosmedicos', '0007_alter_horario_hora_desde'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='obra_social',
            field=models.IntegerField(default=0, verbose_name='Obra Social'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_hasta',
            field=models.TimeField(default='2023-12-11 12:00', verbose_name='hora de fin de consulta'),
        ),
    ]
